FROM rust:1.40 as builder
WORKDIR /usr/src/sinkserver
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
COPY --from=builder /usr/local/cargo/bin/sinkserver /usr/local/bin/sinkserver
CMD ["sinkserver"]