FROM rust:1.40 as builder
WORKDIR /usr/src/sinkclient
COPY . .
RUN cargo install --bin sinkclient --path .

FROM debian:buster-slim
COPY --from=builder /usr/local/cargo/bin/sinkclient /usr/local/bin/sinkclient
CMD ["sinkclient"]